package eventtracker.model;

import java.util.Map;
import java.util.Objects;

/**
 * ============================================================
 * TRACK REQUEST — Batch ingestion input record
 * ============================================================
 *
 * Lightweight request object for bulk event imports via trackBatch().
 * Contains only caller-provided fields; eventId, timestamp, and sessionId
 * are generated by the tracker itself.
 *
 * Why a separate record from Event?
 *   - Event has generated fields (eventId, timestamp, sessionId)
 *   - TrackRequest has only user-supplied fields
 *   - Clean separation of "what the caller provides" vs "what the system generates"
 *   - Prevents callers from accidentally supplying conflicting IDs or timestamps
 *
 * This pattern mirrors real SDK APIs:
 *   Segment: analytics.track({userId, event, properties})
 *   Mixpanel: mixpanel.track(event_name, properties)
 */
public record TrackRequest(
        String userId,
        String eventType,
        Map<String, Object> properties
) {
    public TrackRequest {
        Objects.requireNonNull(userId, "userId must not be null");
        Objects.requireNonNull(eventType, "eventType must not be null");
        if (properties == null) properties = Map.of();
    }
}
